### ISSUE TITLE
Dynamic graph conflicts in WeBWorK exercise knowls

### ISSUE THREAD

**Issue by sean-fitzpatrick** [APEXCalculus/APEXCalculusPTX#8]
I noticed a bug yesterday that's present in the apex-mbx HTML build.

If you have multiple WW exercises on a page with dynamic graphs in them:

1. Open a knowl for one exercise. You'll see the graph for that question. Good.
2. Open a knowl for a second exercise. The graph for that exercise will replace the graph in the previously opened knowl(s).

It doesn't matter if you close the first exercise knowl or leave it open.

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan I believe this is resolved, yes? I'll leave it for you to confirm and close.

**Comment by Alex-Jordan** [comment]
I *think* it is not really resolved. But when problems use different seeds, that is adequate. Maybe keep this here as a reminder for me to address the real issue.

**Comment by sean-fitzpatrick** [comment]
The WeBWorK build script now uses seed N for problem N, so we no longer have to worry about two problems using the same seed.

Also, maybe there will be time this summer to purge all of these and replace them with TikZ, since that is now supported in WeBWorK.
